# 构建 Jekyll 站点并将其部署到 GitHub Pages 的示例工作流程
姓名：Deploy Jekyll with GitHub Pages dependencies preinstalled

在：
  # 在针对默认分支的推送上运行
  推：
    分支：[ “主要” ]

  # 允许您从“操作”选项卡手动运行此工作流程
  工作流程_调度：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  内容：read
  页面：write
  id 令牌：write

# 仅允许一项并发部署，跳过正在进行的运行和最新排队的运行之间的排队运行。
# 但是，不要取消正在进行的运行，因为我们希望完成这些生产部署。
并发：
  组：“页面”
  取消进行中：false

工作：
  # 构建作业
  建造者：
    运行：ubuntu-latest
    脚步：
      -姓名：结账
        用途：actions/checkout@v4
      -名称：设置页面
        用途：actions/configure-pages@v5
      -名称：Build with Jekyll
        用途：actions/jekyll-build-pages@v1
        和：
          来源： 。/
          目的地：./_site
      -姓名：Upload artifact
        用途：actions/upload-pages-artifact@v3

  # 部署作业
  部署：
    环境：
      姓名：github-pages
      网址：${ { steps.deployment.outputs.page_url } }
    运行：ubuntu-latest
    需求：build
    脚步：
      -姓名：Deploy to GitHub Pages
        ID ：deployment
        使用：actions/deploy-pages@v4
